name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./shopapp.webui
    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: ./shopapp.webui
    - name: Publish
      run: dotnet publish --no-build -c Release -o ./publish
      working-directory: ./shopapp.webui
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
         name: my-artifact
